version: 2.0.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
  - dev
configuration: Release
before_build:
- ps: >-
    dotnet --info
    nuget restore
    dotnet restore
build_script:
- ps: dotnet build
test_script:
- ps: dotnet test ./src/NetCoreForce.Client.Tests/NetCoreForce.Client.Tests.csproj